<a id="1"></a>
# <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center; padding: 10px;border-radius:10px 10px;">TP 01 : Nettoyage de Données</p>


# <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center; padding: 5px;border-radius:10px 10px;">Boston Dataset</p>

- importation des libriries

In [54]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

- importation de donnée

In [55]:
boston = pd.read_csv("./boston.csv")
boston.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,5506,https://www.airbnb.com/rooms/5506,20191204162830,2019-12-04,**$79 Special ** Private! Minutes to center!,"Private guest room with private bath, You do n...",**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Private guest room with private bath, You do n...",none,"Peacful, Architecturally interesting, historic...",...,t,f,strict_14_with_grace_period,f,f,6,6,0,0,0.81
1,6695,https://www.airbnb.com/rooms/6695,20191204162830,2019-12-04,$99 Special!! Home Away! Condo,"Comfortable, Fully Equipped private apartment...",** WELCOME *** FULL PRIVATE APARTMENT In a His...,"Comfortable, Fully Equipped private apartment...",none,"Peaceful, Architecturally interesting, histori...",...,t,f,strict_14_with_grace_period,f,f,6,6,0,0,0.91
2,8789,https://www.airbnb.com/rooms/8789,20191204162830,2019-12-04,Curved Glass Studio/1bd facing Park,"Bright, 1 bed with curved glass windows facing...",Fully Furnished studio with enclosed bedroom. ...,"Bright, 1 bed with curved glass windows facing...",none,Beacon Hill is a historic neighborhood filled ...,...,f,f,strict_14_with_grace_period,f,f,10,10,0,0,0.37
3,10730,https://www.airbnb.com/rooms/10730,20191204162830,2019-12-04,Bright 1bed facing Golden Dome,"Bright, spacious unit, new galley kitchen, new...",Bright one bed facing the golden dome of the S...,"Bright, spacious unit, new galley kitchen, new...",none,Beacon Hill is located downtown and is conveni...,...,f,f,strict_14_with_grace_period,f,f,10,10,0,0,0.24
4,10811,https://www.airbnb.com/rooms/10811,20191204162830,2019-12-04,"Back Bay Apt Studio-3 blocks to Pru center & ""T""",Stunning Back Bay furnished studio apartment. ...,"Back Bay Studio Apt - Private bath, A/C, Cabl...",Stunning Back Bay furnished studio apartment. ...,none,A one-square mile neighborhood that is arguabl...,...,f,f,strict_14_with_grace_period,f,f,7,7,0,0,0.19

- Information sur notre dataset:

In [56]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3507 entries, 0 to 3506
Columns: 106 entries, id to reviews_per_month
dtypes: float64(23), int64(21), object(62)
memory usage: 2.8+ MB

In [57]:
print(f"- nombre des lignes {boston.shape[0]}\n- nombre des colonnes {boston.shape[1]}")
print("Les noms des colonnes", boston.columns)

- nombre des lignes 3507
- nombre des colonnes 106
Les noms des colonnes Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

- Description des données : Des measures standart pour bien compredre la dispression des données comme : Min, Max, mean...

In [58]:
boston.describe()

,id,scrape_id,thumbnail_url,medium_url,xl_picture_url,host_id,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.507000e+03,3.507000e+03,0.0,0.0,0.0,3.507000e+03,0.0,3492.000000,3492.000000,0.0,...,2812.000000,2810.000000,2813.000000,2811.000000,2811.000000,3507.000000,3507.000000,3507.000000,3507.000000,2823.000000
mean,2.302483e+07,2.019120e+13,NaN,NaN,NaN,8.078523e+07,NaN,155.973081,155.973081,NaN,...,9.481152,9.726335,9.673303,9.578798,9.246176,28.414314,25.100371,3.220131,0.035358,2.200712
std,1.177855e+07,0.000000e+00,NaN,NaN,NaN,9.195359e+07,NaN,325.392676,325.392676,NaN,...,0.857304,0.769328,0.825613,0.762394,0.964060,44.020580,43.917254,6.939270,0.380506,2.221209
min,5.506000e+03,2.019120e+13,NaN,NaN,NaN,7.969000e+03,NaN,0.000000,0.000000,NaN,...,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.377961e+07,2.019120e+13,NaN,NaN,NaN,1.163189e+07,NaN,2.000000,2.000000,NaN,...,9.000000,10.000000,10.000000,9.000000,9.000000,1.000000,0.000000,0.000000,0.000000,0.460000
50%,2.354402e+07,2.019120e+13,NaN,NaN,NaN,3.028359e+07,NaN,6.000000,6.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,9.000000,6.000000,1.000000,0.000000,0.000000,1.480000
75%,3.331801e+07,2.019120e+13,NaN,NaN,NaN,1.334577e+08,NaN,43.000000,43.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,10.000000,27.000000,22.000000,3.000000,0.000000,3.345000
max,4.057364e+07,2.019120e+13,NaN,NaN,NaN,3.132551e+08,NaN,1068.000000,1068.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,10.000000,147.000000,147.000000,33.000000,5.000000,15.000000

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;padding:5px;border-radius:10px 10px;">Feature Engireneering</p>

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;border-radius:10px 10px;padding:5px;">Dropping columns that are of no use</p>

### Suppression selon le nombre des valeurs nulles :

- Les colonnes contenant plus de 70 % de valeurs manquantes seront supprimées.

In [59]:
columns_to_drop = []
for column in boston.columns:
    null_count = boston[column].isna().sum()
    total_rows = boston.shape[0]
    if (null_count / total_rows) >= 0.7:
        columns_to_drop.append(column)
        print(f"{column}: {null_count}")

thumbnail_url: 3507
medium_url: 3507
xl_picture_url: 3507
host_acceptance_rate: 3507
neighbourhood_group_cleansed: 3507
square_feet: 3383
weekly_price: 3215
monthly_price: 3211

In [60]:
boston.drop(columns=columns_to_drop, axis=1, inplace=True)
print(f" - Le nombre de colonnes supprimées est : {len(columns_to_drop)}")
print(" - Les noms des colonnes supprimées : \n", columns_to_drop )
print("\n - Le nombre des colonnes restent :", len(boston.columns))

 - Le nombre de colonnes supprimées est : 8
 - Les noms des colonnes supprimées :
 ['thumbnail_url', 'medium_url', 'xl_picture_url', 'host_acceptance_rate', 'neighbourhood_group_cleansed', 'square_feet', 'weekly_price', 'monthly_price']

 - Le nombre des colonnes restent : 98

### - Suppression selon le nombre des enregitrements dupliquées :

In [61]:
nbr_duplicate = boston.duplicated().sum()
print("- Le nombre des doublons dans notre dataset est: ", nbr_duplicate)
print("- Le nombre des colonnes restent :", len(boston.columns))

- Le nombre des doublons dans notre dataset est:  0
- Le nombre des colonnes restent : 98

### - Suppression des villes qui n'appartiennent pas à Boston

In [62]:
cities_to_remove = ['Brookline', 'Somerville', 
                    '88 Auckland Street, Apt 1, Dorchester, MA 0212', 
                    'Everett', 'Cambridge']

boston = boston[~boston['city'].isin(cities_to_remove)]
boston["city"].unique()

array(['Boston', 'Charlestown', 'Roslindale', 'Jamaica Plain', 'Brighton',
       'Dorchester', 'Boston (Jamaica Plain)', '波士顿', 'Boston ',
       'ALLSTON', 'Allston', 'West Roxbury', 'East Boston', 'Boston, ',
       'Jamaica Plain, Boston', 'Roxbury Crossing', 'Jamaica Plain ',
       'Mattapan ', 'Hyde Park ', 'Hyde Park', 'Dorchester ', nan,
       'Dorchester,', 'BOSTON', 'ROXBURY CROSSING', 'Brighton '],
      dtype=object)

- Encoder la colonne "city"

In [63]:
label_encoder = LabelEncoder()
boston['city_encoded'] = label_encoder.fit_transform(boston['city'])
boston = boston.drop(columns=['city'])
boston['city_encoded'].head(3)

0    3
1    3
2    3
Name: city_encoded, dtype: int32

### Suppression selon le nombre des valeurs uniques:

- Au sein de cette section, nous avons exclu toutes les colonnes ne contenant qu'une seule valeur unique répétée dans la totalité de la colonne.

On observe que le colonne "experiences_offered" ne contient qu'une des valeurs none, Il faut le supprimer aussi

In [64]:
#Les valeurs uniques du colonne "experiences_offered"
boston["experiences_offered"].unique()

array(['none'], dtype=object)

In [65]:
boston = boston.drop(columns=["experiences_offered"], axis=1)

In [66]:
# Pour chaque colonne en affiche les noms des colonnes ayant un nombre des valeurs uniques qui égale a 1 et le supprimer
cols_to_remove = [col for col in boston.columns if len(boston[col].unique()) == 1]
print(f"-Les colonnes a une seule valeur unique:\n {cols_to_remove}\n-total des colonnes supprimées: {len(cols_to_remove)}")
# Supprimer les colonnes du DataFrame
boston = boston.drop(cols_to_remove, axis=1)

-Les colonnes a une seule valeur unique:
 ['scrape_id', 'country_code', 'country', 'has_availability', 'requires_license', 'is_business_travel_ready']
-total des colonnes supprimées: 6

In [67]:
print("- Le nombre des colonnes restent :", len(boston.columns))

- Le nombre des colonnes restent : 91

### - Suppression des identifiants et des données ont une relation avec celles récupérées

In [68]:
boston.drop(columns=['id', 'last_scraped', 'host_id'], axis=1, inplace=True)

### Suppression selon le type:

- Dans cette section, nous allons lister le type de chaque colonne.
Pour les colonnes textuelles qui ne présentent aucune modalité, elles seront supprimées.
- Si une colonne textuelle contient des catégories spécifiques inferieurs de 10 modalitées , elles seront représentées numériquement.
- En ce qui concerne les colonnes numériques, nous examinerons leurs corrélations et supprimerons l'une d'entre elles en cas de corrélation élevée entre elles.

In [69]:
# les type de chaque colonne
column_types = boston.dtypes
columns_to_drop = []
# Suppression des colonnes textuelles avec plus de 10 modalités
text_columns = column_types[column_types == 'object'].index
for column in text_columns:
    if len(boston[column].unique()) >= 10:
        boston = boston.drop(columns=[column])
        columns_to_drop.append(column)
print(f"- Le nombre des colonnes textuelles supprimées est: {len(columns_to_drop)},\n- Les noms des colonnes: {columns_to_drop} ")
print("- Le nombre des colonnes restent :", len(boston.columns))

- Le nombre des colonnes textuelles supprimées est: 37,
- Les noms des colonnes: ['listing_url', 'name', 'summary', 'space', 'description', 'neighborhood_overview', 'notes', 'transit', 'access', 'interaction', 'house_rules', 'picture_url', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about', 'host_response_rate', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_verifications', 'street', 'neighbourhood', 'neighbourhood_cleansed', 'zipcode', 'smart_location', 'property_type', 'amenities', 'price', 'security_deposit', 'cleaning_fee', 'extra_people', 'calendar_updated', 'first_review', 'last_review', 'license']
- Le nombre des colonnes restent : 51

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;padding:5px;border-radius:10px 10px;">Data Labelling</p>

- Représentation numérique des catégories des colonnes textuelles ayant des modalités limitées

In [70]:
col_to_numeriques=[]
for column in text_columns:
    if column in boston.columns and len(boston[column].unique()) > 1:
        boston[column] = pd.Categorical(boston[column]).codes
        col_to_numeriques.append(column)

In [71]:
print(f"Les colonnes textuelles qu'on a encoder en format numériques sont:\n {col_to_numeriques}")
boston.head(2)

Les colonnes textuelles qu'on a encoder en format numériques sont:
 ['host_response_time', 'host_is_superhost', 'host_has_profile_pic', 'host_identity_verified', 'state', 'market', 'is_location_exact', 'room_type', 'bed_type', 'calendar_last_scraped', 'jurisdiction_names', 'instant_bookable', 'cancellation_policy', 'require_guest_profile_picture', 'require_guest_phone_verification']

,host_response_time,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,state,market,latitude,longitude,...,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
0,3,0,6.0,6.0,1,1,1,0,42.32981,-71.09559,...,1,3,0,0,6,6,0,0,0.81,3
1,3,0,6.0,6.0,1,1,1,0,42.32994,-71.09351,...,1,3,0,0,6,6,0,0,0.91,3

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;border-radius:10px 10px;padding:5px">Data Transform</p>

### - Nous allons transférer 't' à 1 et 'f' à 0 dans ces colonnes

In [72]:
columns_to_transform = ['host_is_superhost', 'host_has_profile_pic', 'host_identity_verified', 'is_location_exact', 
                        'has_availability', 'requires_license', 'instant_bookable', 'is_business_travel_ready', 
                        'require_guest_profile_picture', 'require_guest_phone_verification']
mapping = {'t': 1, 'f': 0, 'nan': 0, np.nan: 0}

existing_columns = [col for col in columns_to_transform if col in boston.columns]

boston[existing_columns] = boston[existing_columns].replace(mapping)

In [73]:
boston.head(3)

,host_response_time,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,state,market,latitude,longitude,...,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
0,3,0,6.0,6.0,1,1,1,0,42.32981,-71.09559,...,1,3,0,0,6,6,0,0,0.81,3
1,3,0,6.0,6.0,1,1,1,0,42.32994,-71.09351,...,1,3,0,0,6,6,0,0,0.91,3
2,2,1,12.0,12.0,1,0,1,0,42.35919,-71.06265,...,0,3,0,0,10,10,0,0,0.37,3

### - Convertir la colonne 'prix' 'security_deposit' 'cleaning_fee' 'extra_people' en float

In [74]:
boston.columns = boston.columns.str.strip()
columns_to_transform = ['price', 'security_deposit', 'cleaning_fee', 'extra_people']

for col in columns_to_transform:
    if col in boston.columns:
        if boston[col].dtype == 'object':
            boston[col] = boston[col].str.replace('[\$,]', '', regex=True)
            # Convert values to float
            boston[col] = boston[col].astype(float)

In [75]:
boston.head(3)

,host_response_time,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,state,market,latitude,longitude,...,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
0,3,0,6.0,6.0,1,1,1,0,42.32981,-71.09559,...,1,3,0,0,6,6,0,0,0.81,3
1,3,0,6.0,6.0,1,1,1,0,42.32994,-71.09351,...,1,3,0,0,6,6,0,0,0.91,3
2,2,1,12.0,12.0,1,0,1,0,42.35919,-71.06265,...,0,3,0,0,10,10,0,0,0.37,3

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;border-radius:10px 10px;padding:5px;">Filling missing values</p>

### La Remplissage des colonnes ayant des valeurs manquantes telles que :


- Les colonnes qui sont contient des valeurs réelsn nous avaons utilisées la moyenne pour les remplires.
- Les colonnes qui sont contient des modalités, nous avaons utilisées le mode pour les remplires.

- la moyenne

In [76]:
colonnes_specifiees = ['host_listings_count', 'host_total_listings_count', 
                        'review_scores_rating', 'reviews_per_month']

for colonne in colonnes_specifiees:
    moyenne_colonne = boston[colonne].mean()
    boston[colonne].fillna(moyenne_colonne, inplace=True)

- le mode

In [77]:
colonnes_specifiees = ['bathrooms', 'bedrooms', 'review_scores_accuracy', 'review_scores_cleanliness', 
                       'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 
                       'review_scores_value', "beds"]

for colonne in colonnes_specifiees:
    mode = boston[colonne].value_counts().idxmax()
    boston[colonne].fillna(mode, inplace=True)

In [78]:
boston.isnull().sum()

host_response_time                              0
host_is_superhost                               0
host_listings_count                             0
host_total_listings_count                       0
host_has_profile_pic                            0
host_identity_verified                          0
state                                           0
market                                          0
latitude                                        0
longitude                                       0
is_location_exact                               0
room_type                                       0
accommodates                                    0
bathrooms                                       0
bedrooms                                        0
beds                                            0
bed_type                                        0
guests_included                                 0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
calendar_last_scraped                           0
number_of_reviews                               0
number_of_reviews_ltm                           0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
jurisdiction_names                              0
instant_bookable                                0
cancellation_policy                             0
require_guest_profile_picture                   0
require_guest_phone_verification                0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
city_encoded                                    0
dtype: int64

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;border-radius:10px 10px;padding:5px">correlation matrix</p>

- Concernant les colonnes numériques,
- Nous examinerons leurs corrélations et supprimerons l'une d'entre elles en cas de corrélation élevée entre elles.

In [79]:
column_types = boston.dtypes
numeric_columns = column_types[column_types != 'object'].index
correlation_matrix = boston[numeric_columns].corr()
correlation_matrix.T.head(3)

,host_response_time,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,state,market,latitude,longitude,...,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
host_response_time,1.000000,0.226380,0.137602,0.137602,0.155190,-0.067623,-0.009568,-0.019145,-0.008317,0.145511,...,0.249598,0.273354,0.091222,0.064176,0.228659,0.202420,0.164959,0.006591,0.276463,-0.001247
host_is_superhost,0.226380,1.000000,-0.278743,-0.278743,0.182942,0.099108,0.010141,0.001678,-0.078649,-0.027695,...,-0.049874,-0.095775,-0.077641,-0.093125,-0.299649,-0.281412,-0.124764,-0.049200,0.331640,-0.002324
host_listings_count,0.137602,-0.278743,1.000000,1.000000,0.004955,-0.053391,0.008095,0.016015,0.196777,0.151282,...,0.228961,0.005816,0.477319,0.451494,0.916260,0.945774,-0.167659,-0.041816,-0.200860,-0.060794

Liste pour stocker les paires de colonnes fortement corrélées

In [80]:
seuil_correlation = 0.85

colonnes_a_supprimer = []
for i in range(len(correlation_matrix.columns)):
    for j in range(i+1, len(correlation_matrix.columns)):
        if abs(correlation_matrix.iloc[i, j]) > seuil_correlation:
            colonnes_a_supprimer.append((correlation_matrix.columns[i], correlation_matrix.columns[j]))

Afficher les paires de colonnes fortement corrélées

In [81]:
print("\nColonnes fortement corrélées :")
for colonne1, colonne2 in colonnes_a_supprimer:
    print(f"{colonne1} - {colonne2} : {correlation_matrix.loc[colonne1, colonne2]}")

Colonnes fortement corrélées :
host_listings_count - host_total_listings_count : 1.0
host_listings_count - calculated_host_listings_count : 0.9162604827297202
host_listings_count - calculated_host_listings_count_entire_homes : 0.9457739162427965
host_total_listings_count - calculated_host_listings_count : 0.9162604827297202
host_total_listings_count - calculated_host_listings_count_entire_homes : 0.9457739162427965
minimum_nights - minimum_minimum_nights : 0.968394816501031
minimum_nights - maximum_minimum_nights : 0.9384516227672093
minimum_nights - minimum_nights_avg_ntm : 0.9613891236042608
maximum_nights - minimum_maximum_nights : 0.8665986925565248
maximum_nights - maximum_maximum_nights : 0.8739745495614973
maximum_nights - maximum_nights_avg_ntm : 0.873902936322002
minimum_minimum_nights - maximum_minimum_nights : 0.9092609976424505
minimum_minimum_nights - minimum_nights_avg_ntm : 0.9470701024055681
maximum_minimum_nights - minimum_nights_avg_ntm : 0.985602956963614
minimum_maximum_nights - maximum_maximum_nights : 0.9961425989459893
minimum_maximum_nights - maximum_nights_avg_ntm : 0.996287677518332
maximum_maximum_nights - maximum_nights_avg_ntm : 0.9999962623738782
availability_30 - availability_60 : 0.9119995051128897
availability_60 - availability_90 : 0.9722662972924456
calculated_host_listings_count - calculated_host_listings_count_entire_homes : 0.987405942125446

- Supprimer l'une des colonnes de chaque paire fortement corrélée :
- On va Supprimer la colonne avec la plus faible variance

In [82]:
for colonne1, colonne2 in colonnes_a_supprimer:    
    if colonne1 in boston.columns and colonne2 in boston.columns:
        if boston[colonne1].var() > boston[colonne2].var():
            boston.drop(colonne2, axis=1, inplace=True)
        else:
            boston.drop(colonne1, axis=1, inplace=True)
boston.head(3)

,host_response_time,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,state,market,latitude,longitude,is_location_exact,...,review_scores_value,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
0,3,0,6.0,1,1,1,0,42.32981,-71.09559,1,...,10.0,0,1,3,0,0,0,0,0.81,3
1,3,0,6.0,1,1,1,0,42.32994,-71.09351,1,...,10.0,0,1,3,0,0,0,0,0.91,3
2,2,1,12.0,1,0,1,0,42.35919,-71.06265,1,...,9.0,0,0,3,0,0,0,0,0.37,3

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;border-radius:10px 10px;padding:7px">Data Scaling</p>

In [83]:
numeric_columns = boston.select_dtypes(include=['float64', 'int64']).columns
standard_scaler = StandardScaler()
boston[numeric_columns] = standard_scaler.fit_transform(boston[numeric_columns])
boston.head(3)

,host_response_time,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,state,market,latitude,longitude,is_location_exact,...,review_scores_value,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
0,3,0,-0.462978,1,1,1,0,-0.318723,-0.401216,1,...,0.662314,0,1,3,0,0,-0.46486,-0.093124,-0.698487,3
1,3,0,-0.462978,1,1,1,0,-0.313686,-0.335585,1,...,0.662314,0,1,3,0,0,-0.46486,-0.093124,-0.648371,3
2,2,1,-0.444526,1,0,1,0,0.819583,0.638146,1,...,-0.431005,0,0,3,0,0,-0.46486,-0.093124,-0.918997,3

In [84]:
print("- La taille finale de notre dataset :", boston.shape)

- La taille finale de notre dataset : (3493, 40)

- Voila, notre dataset maintenant a été bien nettoyée.

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;border-radius:10px 10px;padding:10px">Cambridge Dataset</p>

- importation de donnée

In [85]:
data = pd.read_csv("cambridge.csv")
data.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,8521,https://www.airbnb.com/rooms/8521,20191126082128,2019-11-26,SunsplashedSerenity near Harvard $1300/wk flex...,"An elegant, sun-splashed, 2 bedroom (+2offices...","An elegant, sun-splashed, 2+ bedroom apartment...","An elegant, sun-splashed, 2 bedroom (+2offices...",none,Huron Village is known for its charm. We have...,...,f,f,strict_14_with_grace_period,f,f,3,3,0,0,0.26
1,11169,https://www.airbnb.com/rooms/11169,20191126082128,2019-11-26,Lovely Studio Room: Thu-Mons Near Universities!,Large sunny room which comfortably fits a coup...,"We have a peaceful, large, sunny room w/ attac...",Large sunny room which comfortably fits a coup...,none,The neighborhood is quiet and friendly and our...,...,f,f,strict_14_with_grace_period,t,t,4,1,3,0,1.22
2,11945,https://www.airbnb.com/rooms/11945,20191126082128,2019-11-26,Near Harvard: Safe & Lovely Room,Room next to kitchen and living room in wonder...,"Quiet peaceful room w/shared marble bath, wifi...",Room next to kitchen and living room in wonder...,none,Amazing neighborhood: Quiet yet close walk to ...,...,f,f,strict_14_with_grace_period,t,t,4,1,3,0,0.27
3,19581,https://www.airbnb.com/rooms/19581,20191126082128,2019-11-26,"Furnished suite, Windsor","Welcome to Area IV! We are located, convenient...","Furnished suite at the Windsor Inn, Cambridge....","Welcome to Area IV! We are located, convenient...",none,NaN,...,f,f,strict_14_with_grace_period,f,f,3,0,3,0,0.05
4,22006,https://www.airbnb.com/rooms/22006,20191126082128,2019-11-26,B & B near Harvard's Quad Houses,"Two comfortable guest rooms in quiet, tree-fil...","Comfortable, convenient B&B at the north end o...","Two comfortable guest rooms in quiet, tree-fil...",none,"We're in a beautiful neighborhood, with nearby...",...,f,f,moderate,f,f,1,0,1,0,0.89

- Information sur notre dataset:

In [86]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Columns: 106 entries, id to reviews_per_month
dtypes: float64(22), int64(22), object(62)
memory usage: 1.0+ MB

In [87]:
print(f"- nombre des lignes {data.shape[0]}\n- nombre des colonnes {data.shape[1]}")
print("Les noms des colonnes", data.columns)

- nombre des lignes 1277
- nombre des colonnes 106
Les noms des colonnes Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

Description générale sur notre dataset

In [88]:
data.describe()

,id,scrape_id,thumbnail_url,medium_url,xl_picture_url,host_id,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,1.277000e+03,1.277000e+03,0.0,0.0,0.0,1.277000e+03,0.0,1276.000000,1276.000000,0.0,...,1087.000000,1087.000000,1087.000000,1087.000000,1087.000000,1277.000000,1277.000000,1277.000000,1277.000000,1099.000000
mean,2.072702e+07,2.019113e+13,NaN,NaN,NaN,6.899113e+07,NaN,66.994514,66.994514,NaN,...,9.456302,9.805888,9.774609,9.846366,9.311868,6.401723,3.498825,2.886453,0.016445,2.053130
std,1.203935e+07,0.000000e+00,NaN,NaN,NaN,7.885114e+07,NaN,232.805901,232.805901,NaN,...,0.932172,0.662076,0.671561,0.540567,0.882236,9.336571,6.861097,6.385631,0.127228,2.174205
min,8.521000e+03,2.019113e+13,NaN,NaN,NaN,3.538400e+04,NaN,0.000000,0.000000,NaN,...,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.020000
25%,1.036623e+07,2.019113e+13,NaN,NaN,NaN,9.419684e+06,NaN,1.000000,1.000000,NaN,...,9.000000,10.000000,10.000000,10.000000,9.000000,1.000000,0.000000,0.000000,0.000000,0.390000
50%,2.120450e+07,2.019113e+13,NaN,NaN,NaN,3.608504e+07,NaN,3.000000,3.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,9.000000,3.000000,1.000000,1.000000,0.000000,1.130000
75%,3.126584e+07,2.019113e+13,NaN,NaN,NaN,9.820703e+07,NaN,9.000000,9.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,10.000000,6.000000,2.000000,3.000000,0.000000,3.195000
max,4.032730e+07,2.019113e+13,NaN,NaN,NaN,3.116287e+08,NaN,1795.000000,1795.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,10.000000,41.000000,35.000000,33.000000,1.000000,10.920000

# -  Dropping columns that are of no use

### Suppression selon le nombre des valeurs nulles :

- Les colonnes contenant plus de 70 % de valeurs manquantes seront supprimées.

In [89]:
columns_to_drop = []
for column in data.columns:
    null_count = data[column].isna().sum()
    total_rows = data.shape[0]
    if (null_count / total_rows) >= 0.7:
        columns_to_drop.append(column)
        print(f"{column}: {null_count}")

thumbnail_url: 1277
medium_url: 1277
xl_picture_url: 1277
host_acceptance_rate: 1277
neighbourhood_group_cleansed: 1277
square_feet: 1268
weekly_price: 1112
monthly_price: 1120
license: 1182

In [90]:
data.drop(columns=columns_to_drop, axis=1, inplace=True)

### - Suppression selon le nombre des enregitrements dupliquées :

In [91]:
nbr_duplicate = data.duplicated().sum()
print("- Le nombre des doublons dans notre dataset est: ", nbr_duplicate)
print("- Le nombre des colonnes restent :", len(data.columns))

- Le nombre des doublons dans notre dataset est:  0
- Le nombre des colonnes restent : 97

### Suppression des villes qui n'appartiennent pas à Cambridge

In [92]:
cities_to_remove = ['Somerville', 'Watertown', 'Arlington', 
                    'Belmont', 'Boston', 'Brookline' ]

data = data[~data['city'].isin(cities_to_remove)]

- Encoder la colonne "city"

In [93]:
label_encoder = LabelEncoder()
data['city_encoded'] = label_encoder.fit_transform(data['city'])
data = data.drop(columns=['city'])
data['city_encoded'].head(3)

0    0
1    0
2    0
Name: city_encoded, dtype: int32

- Suppression des identifiants et des données ont une relation avec celles récupérées

In [94]:
data.drop(columns=['id', 'scrape_id', 'last_scraped', 'host_id'], axis=1, inplace=True)

## Data Transform

### - Nous allons transférer 't' à 1 et 'f' à 0 dans ces colonnes

In [95]:
columns_to_transform = ['require_guest_profile_picture', 'require_guest_phone_verification', 'requires_license', 'instant_bookable',   
                        'is_business_travel_ready', 'has_availability', 'is_location_exact', 'host_has_profile_pic', 
                        'host_identity_verified']

mapping = {'t': 1, 'f': 0, 'nan': 0, np.nan: 0}

data[columns_to_transform] = data[columns_to_transform].replace(mapping)

### - Convertir la colonne 'price' 'extra_people' 'cleaning_fee' 'security_deposit' en float

In [96]:
# Remove non-numeric characters ('$' and ',') from the values in the columns
data['price'] = data['price'].str.replace('[\$,]', '', regex=True)
data['extra_people'] = data['extra_people'].str.replace('[\$,]', '', regex=True)
data['cleaning_fee'] = data['cleaning_fee'].str.replace('[\$,]', '', regex=True)
data['security_deposit'] = data['security_deposit'].str.replace('[\$,]', '', regex=True)

# Convert the values in the columns to float
data['price'] = data['price'].astype(float)
data['extra_people'] = data['extra_people'].astype(float)
data['cleaning_fee'] = data['cleaning_fee'].astype(float)
data['security_deposit'] = data['security_deposit'].astype(float)

### - Suppression toutes les colonnes de type object

In [97]:
object_column = []
for column in data.columns :
    if data[column].dtype == 'object' :
        object_column.append(column)
object_column

['listing_url',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'picture_url',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_verifications',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'state',
 'zipcode',
 'market',
 'smart_location',
 'country_code',
 'country',
 'property_type',
 'room_type',
 'bed_type',
 'amenities',
 'calendar_updated',
 'calendar_last_scraped',
 'first_review',
 'last_review',
 'jurisdiction_names',
 'cancellation_policy']

In [98]:
data.drop(columns=object_column, axis=1, inplace=True)

In [99]:
print("Le nombre de colonnes restent est: ", len(data.columns))

Le nombre de colonnes restent est:  49

## Filling missing values

- Par la moyenne

In [100]:
colonnes_specifiees = ['host_listings_count', 'host_total_listings_count', 'reviews_per_month']

for colonne in colonnes_specifiees:
    moyenne_colonne = data[colonne].mean()
    data[colonne].fillna(moyenne_colonne, inplace=True)

- Par le mode

In [101]:
colonnes_specifiees = ['beds', 'security_deposit', 'cleaning_fee', 'review_scores_rating', 'review_scores_accuracy',  
                       'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication',  
                       'review_scores_location', 'review_scores_value']

for colonne in colonnes_specifiees:
    mode = data[colonne].value_counts().idxmax()
    data[colonne].fillna(mode, inplace=True)

In [102]:
data.isna().sum()

host_listings_count                             0
host_total_listings_count                       0
host_has_profile_pic                            0
host_identity_verified                          0
latitude                                        0
longitude                                       0
is_location_exact                               0
accommodates                                    0
bathrooms                                       0
bedrooms                                        0
beds                                            0
price                                           0
security_deposit                                0
cleaning_fee                                    0
guests_included                                 0
extra_people                                    0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
has_availability                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
number_of_reviews                               0
number_of_reviews_ltm                           0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
requires_license                                0
instant_bookable                                0
is_business_travel_ready                        0
require_guest_profile_picture                   0
require_guest_phone_verification                0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
city_encoded                                    0
dtype: int64

## La matrice de Corrélation

In [103]:
matrix_corr = data.corr()
matrix_corr.head()

,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,latitude,longitude,is_location_exact,accommodates,bathrooms,bedrooms,...,instant_bookable,is_business_travel_ready,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
host_listings_count,1.000000e+00,1.000000e+00,-9.378433e-16,-0.139355,-0.171793,0.281605,-0.085881,-0.031392,-0.025581,-0.085076,...,0.019783,NaN,-0.041042,0.038441,0.528828,0.799999,-0.085911,-0.036615,-0.083431,-0.019471
host_total_listings_count,1.000000e+00,1.000000e+00,-9.378433e-16,-0.139355,-0.171793,0.281605,-0.085881,-0.031392,-0.025581,-0.085076,...,0.019783,NaN,-0.041042,0.038441,0.528828,0.799999,-0.085911,-0.036615,-0.083431,-0.019471
host_has_profile_pic,-9.378433e-16,-9.378433e-16,1.000000e+00,0.028330,-0.004334,0.028851,-0.011616,-0.012092,0.014348,-0.021146,...,-0.032862,NaN,0.004287,0.006792,0.016479,0.010404,0.012829,0.003702,0.002497,0.001950
host_identity_verified,-1.393548e-01,-1.393548e-01,2.832960e-02,1.000000,0.092061,-0.098158,0.073278,-0.047481,0.058820,0.007416,...,-0.227369,NaN,0.097229,0.084498,-0.015345,-0.166604,0.156923,-0.018786,-0.149813,0.003997
latitude,-1.717925e-01,-1.717925e-01,-4.334132e-03,0.092061,1.000000,-0.637645,0.013543,0.012361,0.010398,0.042239,...,0.005623,NaN,0.021342,-0.026134,-0.189813,-0.175105,-0.090610,0.067680,-0.051945,0.009985

- Les colonnes qui ont une forte corrélation entre elles

In [104]:
seuil_corr = 0.85

paires_corr = []

for i in range(len(matrix_corr.columns)):
    for j in range(i+1, len(matrix_corr.columns)):
        if abs(matrix_corr.iloc[i, j]) >= seuil_corr:  # Vérifier si la corrélation est supérieure ou égale au seuil
            paires_corr.append((matrix_corr.columns[i], matrix_corr.columns[j]))

for paire in paires_corr:
    print("{} et {} : {}.".format(paire[0], paire[1], matrix_corr.loc[paire[0], paire[1]]))

host_listings_count et host_total_listings_count : 1.0.
minimum_nights et minimum_minimum_nights : 0.9707679252366395.
minimum_nights et maximum_minimum_nights : 0.9541456536484425.
minimum_nights et minimum_nights_avg_ntm : 0.9910708135722829.
maximum_nights et minimum_maximum_nights : 0.9614757872828674.
maximum_nights et maximum_maximum_nights : 0.9616348063165842.
maximum_nights et maximum_nights_avg_ntm : 0.9616347760335161.
minimum_minimum_nights et maximum_minimum_nights : 0.9247287293706347.
minimum_minimum_nights et minimum_nights_avg_ntm : 0.9669345452794618.
maximum_minimum_nights et minimum_nights_avg_ntm : 0.9824374196239813.
minimum_maximum_nights et maximum_maximum_nights : 0.9998484643206462.
minimum_maximum_nights et maximum_nights_avg_ntm : 0.999849137327948.
maximum_maximum_nights et maximum_nights_avg_ntm : 0.9999999992510301.
availability_30 et availability_60 : 0.8947913688379723.
availability_60 et availability_90 : 0.962985871481796.
number_of_reviews_ltm et reviews_per_month : 0.8503302229437579.

- Supprimer l'une des colonnes de chaque paire fortement corrélée :
- On va Supprimer la colonne avec la plus faible variance.

In [105]:
for colonne1, colonne2 in colonnes_a_supprimer:    
    if colonne1 in data.columns and colonne2 in data.columns:
        if data[colonne1].var() > data[colonne2].var():
            data.drop(colonne2, axis=1, inplace=True)
        else:
            data.drop(colonne1, axis=1, inplace=True)
data.head(3)

,host_total_listings_count,host_has_profile_pic,host_identity_verified,latitude,longitude,is_location_exact,accommodates,bathrooms,bedrooms,beds,...,review_scores_value,requires_license,instant_bookable,is_business_travel_ready,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
0,3.0,1.0,1.0,42.38329,-71.13617,1,5,1.0,2,2.0,...,9.0,1,0,0,0,0,0,0,0.26,0
1,3.0,1.0,1.0,42.39469,-71.13223,1,3,1.0,1,1.0,...,10.0,1,0,0,1,1,3,0,1.22,0
2,3.0,1.0,1.0,42.39454,-71.13431,1,1,1.0,1,1.0,...,10.0,1,0,0,1,1,3,0,0.27,0

# Data Scaling

In [106]:
numeric_columns = data.select_dtypes(include=['float64', 'int64']).columns
standard_scaler = StandardScaler()
data[numeric_columns] = standard_scaler.fit_transform(data[numeric_columns])
data.head()

,host_total_listings_count,host_has_profile_pic,host_identity_verified,latitude,longitude,is_location_exact,accommodates,bathrooms,bedrooms,beds,...,review_scores_value,requires_license,instant_bookable,is_business_travel_ready,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city_encoded
0,-0.278167,0.028307,0.999200,1.221761,-1.675015,0.410343,0.933351,-0.506883,0.747042,0.209899,...,-0.317613,0.0,-0.861383,0.0,-0.151433,-0.239955,-0.453222,-0.130771,-0.885661,0
1,-0.278167,0.028307,0.999200,2.436377,-1.442023,0.410343,-0.079029,-0.506883,-0.469458,-0.661076,...,0.891834,0.0,-0.861383,0.0,6.603570,4.167451,0.012300,-0.130771,-0.413090,0
2,-0.278167,0.028307,0.999200,2.420395,-1.565024,0.410343,-1.091409,-0.506883,-0.469458,-0.661076,...,0.891834,0.0,-0.861383,0.0,6.603570,4.167451,0.012300,-0.130771,-0.880739,0
3,-0.278167,0.028307,0.999200,-0.965613,0.602875,0.410343,-1.091409,-0.506883,-0.469458,-0.661076,...,-1.527060,0.0,-0.861383,0.0,-0.151433,-0.239955,0.012300,-0.130771,-0.989036,0
4,-0.286677,0.028307,-1.000801,1.585080,-0.947652,0.410343,-0.585219,2.375196,-0.469458,-0.661076,...,0.891834,0.0,-0.861383,0.0,-0.151433,-0.239955,-0.298048,-0.130771,-0.575536,0

<a id="1"></a>
## <p style="background-color:#682F2F;font-family:newtimeroman;color:#FFF9ED;font-size:150%;text-align:center;padding:5px;border-radius:10px 10px;">End</p>